name: "\U0001F41E Bug report"
description: File a bug report
labels: ["pending triage"]
body:
  - type: markdown
    attributes:
      value: |
      **Thanks for creating an issue !**

        Please search open/closed issues before submitting. Someone might have asked the same thing before 😉!
  - type: textarea
    id: packages
    attributes:
      label: Target Packages
      description: |
        If the package in which the problem occurred is clear, please tell us the package name and version.
      placeholder: @fastkit/vui@0.13.18
  - type: input
    id: reproduction-link
    attributes:
      label: Link to minimal reproduction
      description: |
        Sandbox environments like [StackBlitz](https://stackblitz.com/) can be used to provide reproducibility.
        If reproduction in a sandbox environment is not appropriate, GitHub repositories can be provided.
      placeholder: Reproduction Link
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        What do we need to do after opening your repro in order to make the bug happen? Clear and concise reproduction instructions are important for us to be able to triage your issue in a timely manner. Note that you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected?
    validations:
      required: true
  - type: textarea
    id: actually-happening
    attributes:
      label: What is actually happening?
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
  - type: textarea
    id: additional-comments
    attributes:
      label: Any additional comments?
      description: e.g. some background/context of how you ran into this bug.
