/**
 * link type
 *
 * @note We need to investigate what this means.
 */
export type MetaDocLinkType = 'link' | 'linkCode' | 'linkPlain';

/**
 * Preview of the symbol a link points at
 *
 * @remarks
 * One level deep by design: it carries the referenced declaration itself, not
 * what that declaration in turn refers to. That keeps the payload bounded and
 * makes a cycle between two symbols harmless.
 */
export interface MetaDocLinkSummary {
  /** Source text of the referenced declaration */
  text: string;
  /**
   * `true` when {@link MetaDocLinkSummary.text} was cut short
   *
   * @remarks A declaration is capped at a fixed number of lines, so that a
   * link to a large interface cannot drag the whole body along with it.
   */
  truncated?: boolean;
  /**
   * Description of the referenced declaration, flattened to plain text
   *
   * @remarks Any `{@link}` inside it collapses to its label, since a preview
   * has no structure of its own to hang a nested link on.
   */
  description?: string;
  /** `true` when the declaration lives outside the project, in `node_modules` */
  external?: boolean;
}

/**
 * link
 *
 * @remarks Usually generated by the link tag
 */
export interface MetaDocLink {
  /** link type */
  type: MetaDocLinkType;
  /** link name */
  name: string;
  /**
   * URL
   * @remarks Only set if a transitionable URL exists
   */
  url?: string;
  /**
   * The symbol reference as written in the tag, such as `"Catcher.from"`
   *
   * @remarks
   * Set instead of {@link MetaDocLink.url} when the tag points at a symbol
   * rather than at a URL. A symbol reference is not transitionable on its own,
   * so a consumer that renders it as an `href` produces a dead anchor.
   */
  target?: string;
  /**
   * Preview of the symbol {@link MetaDocLink.target} names
   *
   * @remarks Only set when the reference resolves to a declaration.
   */
  summary?: MetaDocLinkSummary;
}

/**
 * Comment Analysis Parts
 */
export interface MetaDocPart {
  /** text */
  text: string;
  /** link  */
  link?: MetaDocLink;
}

/**
 * Comment Parsing Results
 */
export interface ParsedComment {
  /** text */
  text: string;
  /** List of Comment Analysis Parts */
  parts: MetaDocPart[];
}

/** Tag Analysis Results */
export interface ParsedTag extends ParsedComment {
  /** tag name */
  name: string;
}

/**
 * Function Parameter Documentation
 */
export interface ParameterDoc extends ParsedComment {
  /** Parameter name */
  parameterName: string;
}

/**
 * Parameter Document Maps
 */
export type ParameterDocs<ParameterName extends string = string> = Record<
  ParameterName,
  ParameterDoc[]
>;

/**
 * Meta Information Documentation
 */
export interface MetaDoc<ParameterName extends string = string> {
  /** description */
  description: ParsedComment;
  /** tags */
  tags: ParsedTag[];
  /** Parameter Document Maps */
  params: ParameterDocs<ParameterName>;
}
