/**
 * link type
 *
 * @note We need to investigate what this means.
 */
export type MetaDocLinkType = 'link' | 'linkCode' | 'linkPlain';

/**
 * link
 *
 * @remarks Usually generated by the link tag
 */
export interface MetaDocLink {
  /** link type */
  type: MetaDocLinkType;
  /** link name */
  name: string;
  /**
   * URL
   * @remarks Only set if a transitionable URL exists
   */
  url?: string;
}

/**
 * Comment Analysis Parts
 */
export interface MetaDocPart {
  /** text */
  text: string;
  /** link  */
  link?: MetaDocLink;
}

/**
 * Comment Parsing Results
 */
export interface ParsedComment {
  /** text */
  text: string;
  /** List of Comment Analysis Parts */
  parts: MetaDocPart[];
}

/** Tag Analysis Results */
export interface ParsedTag extends ParsedComment {
  /** tag name */
  name: string;
}

/**
 * Function Parameter Documentation
 */
export interface ParameterDoc extends ParsedComment {
  /** Parameter name */
  parameterName: string;
}

/**
 * Parameter Document Maps
 */
export type ParameterDocs<ParameterName extends string = string> = Record<
  ParameterName,
  ParameterDoc[]
>;

/**
 * Meta Information Documentation
 */
export interface MetaDoc<ParameterName extends string = string> {
  /** description */
  description: ParsedComment;
  /** tags */
  tags: ParsedTag[];
  /** Parameter Document Maps */
  params: ParameterDocs<ParameterName>;
}
