name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install
        # with:
        #   NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint & Test
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: pnpm lint && pnpm build && pnpm typecheck && pnpm test
