name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install
        # with:
        #   NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint & Test
        run: pnpm lint && pnpm build && pnpm typecheck:packages && pnpm test
